### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by sigvef** [cristeahub/hvilken#5]
Cool project! Is this released to some package manager or something? How can we install this and use it for ourselves (without setting up a full developer setup?)

Looking forward to checking it out!

**Comment by cristeahub** [comment]
I've added macOS prebuilt binaries here as of right now: https://github.com/cristeahub/hvilken/releases/tag/v0.1.0.0

The big drawback is that these are not (yet) notarized, so it's a pain, to be frank, to install it on macOS. Just drop the file in a folder and you can use it from there.

I can also recommend you to add the file to your terminal's $PATH.

When I get notarization and stuff up an running I'll look into adding this to brew.
